
export const CHECKLIST_ITEMS = [
    { key: 'purchaseRequest', label: 'A. Purchase Request(PR) with Individual Program of Works, Scope of work and Drawing/Plan' },
    { key: 'certificateOfFunds', label: 'B. Certificate of Availability of Funds 2025, APP 2025, and Board Resolution NO. 3612 S. 2025' },
    { key: 'publicationInvitation', label: 'C. Publication of Invitation of Bid at the PhilGEPS and PHIVIDEC IA website' },
    { key: 'minutesPreBid', label: 'D. Minutes of Meeting- Pre-Bid Conference' },
    { key: 'biddingDocuments', label: 'E. Bidding Documents(Sec.17,RA9184)' },
    { key: 'supplementalBidBulletin', label: 'F. Supplemental Bid Bulletin #1' },
    { key: 'inviteObservers', label: 'G. Letter Invitation for Observers' },
    { key: 'biddersTechFinancialProposals', label: 'H. Bidders Technical and Financial Proposal' },
    { key: 'abstractBidsOpening', label: 'I. Abstract of Bids as Opening' },
    { key: 'minutesBidOpening', label: 'J. Minutes of meeting- Opening of Bids' },
    { key: 'postingCertification', label: 'K. Posting Certification of BAC Sec Head' },
    { key: 'twgBidEvalReport', label: 'L. TWG Evaluation of Bids Report' },
    { key: 'abstractBidsEvaluated', label: 'M. Abstract of Bids as Evaluated' },
    { key: 'bacResolutionPostQual', label: 'N. BAC Resolution 009 s. 2026(post-qualify LCB)' },
    { key: 'noticePostQual', label: 'O. Notice of Post-Qualification' },
    { key: 'officialReceipt', label: 'O.2. Official Receipt(OLD Checklist)' },
    { key: 'philgepsAwardNotice', label: 'O.4. PhilGEPS Award Notice Abstract(OLD Checklist)' },
    { key: 'endorsementWithBacRes', label: 'P. Endorsement for the Administrator with Attached BAC Resolution 014 s. 2026' },
    { key: 'endorsementForSignature', label: 'Q. Endorsement for the Administrator(for signature)' },
    { key: 'noticeOfAward', label: 'R. Notice of Award (for signature)' },
    { key: 'contractAgreement', label: 'S. Contract Agreement (for signature)' },
    { key: 'noticeToProceed', label: 'T. Notice to Proceed (for signature)' },
];
